export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_CREATE_DETAILS_REQUEST = "ORDER_CREATE_DETAILS_REQUEST";
export const ORDER_CREATE_DETAILS_SUCCESS = "ORDER_CREATE_DETAILS_SUCCESS";
export const ORDER_CREATE_DETAILS_FAIL = "ORDER_CREATE_DETAILS_FAIL";

export const ORDER_USER_LIST_REQUEST = " ORDER_USER_LIST_REQUEST";
export const ORDER_USER_LIST_SUCCESS = "ORDER_USER_LIST_SUCCESS";
export const ORDER_USER_LIST_FAIL = "ORDER_USER_LIST_FAIL";

export const ORDER_USER_DELETE_REQUEST = " ORDER_USER_DELETE_REQUEST";
export const ORDER_USER_DELETE_SUCCESS = "ORDER_USER_DELETE_SUCCESS";
export const ORDER_USER_DELETE_FAIL = "ORDER_USER_DELETE_FAIL";
