export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";

export const POST_PRODUCT_REVIEWS_REQUEST = "POST_PRODUCT_REVIEWS_REQUEST";
export const POST_PRODUCT_REVIEWS_SUCCESS = "POST_PRODUCT_REVIEWS_SUCCESS";
export const POST_PRODUCT_REVIEWS_FAIL = "POST_PRODUCT_REVIEWS_FAIL";
